CREATE TABLE item_rating_aggregates (
    item_id BIGINT UNSIGNED PRIMARY KEY,
    avg_rating DECIMAL(3,2) NOT NULL DEFAULT 0.00,
    rating_count INT UNSIGNED NOT NULL DEFAULT 0,
    rating_1 INT UNSIGNED NOT NULL DEFAULT 0,
    rating_2 INT UNSIGNED NOT NULL DEFAULT 0,
    rating_3 INT UNSIGNED NOT NULL DEFAULT 0,
    rating_4 INT UNSIGNED NOT NULL DEFAULT 0,
    rating_5 INT UNSIGNED NOT NULL DEFAULT 0,
    last_refreshed DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CONSTRAINT fk_item_rating_aggregates_item_id FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
